spring.application.name=ChatApplication

# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}
server.address=0.0.0.0

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO

# ===============================
# STATIC FILES
# ===============================
spring.web.resources.static-locations=classpath:/static/